import httpx

from app.tools.base import BaseTool, ToolError


class WebSearchTool(BaseTool):
    @property
    def name(self) -> str:
        return "web_search"

    @property
    def description(self) -> str:
        return "Search the web and return titles, links, and snippets."

    @property
    def parameters_schema(self):
        return {
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Search query"},
                "num_results": {
                    "type": "integer",
                    "description": "Number of results to return",
                    "minimum": 1,
                    "maximum": 10,
                    "default": 5,
                },
            },
            "required": ["query"],
        }

    async def execute(self, **kwargs):
        query = kwargs.get("query")
        num_results = int(kwargs.get("num_results") or self.config.get("max_search_results") or 5)
        if not query:
            raise ToolError("query is required")

        api_key = self.config.get("google_search_api_key")
        cx = self.config.get("google_search_cx")
        if api_key and cx:
            return await self._google_search(query, num_results, api_key, cx)

        return {
            "query": query,
            "results": [
                {
                    "title": f"Search URL for {query}",
                    "link": "https://www.google.com/search?q=" + query.replace(" ", "+"),
                    "snippet": "Google Custom Search is not configured. Use this URL to inspect current search results.",
                },
                {
                    "title": f"DuckDuckGo search for {query}",
                    "link": "https://duckduckgo.com/?q=" + query.replace(" ", "+"),
                    "snippet": "Fallback search URL generated by the local tool layer.",
                },
            ][:num_results],
            "fallback": True,
        }

    async def _google_search(self, query: str, num_results: int, api_key: str, cx: str):
        params = {
            "key": api_key,
            "cx": cx,
            "q": query,
            "num": min(max(num_results, 1), 10),
        }
        async with httpx.AsyncClient(timeout=15.0) as client:
            response = await client.get("https://www.googleapis.com/customsearch/v1", params=params)
            response.raise_for_status()
        payload = response.json()
        return {
            "query": query,
            "results": [
                {
                    "title": item.get("title", ""),
                    "link": item.get("link", ""),
                    "snippet": item.get("snippet", ""),
                }
                for item in payload.get("items", [])
            ],
            "fallback": False,
        }

    def format_result_for_ai(self, result):
        if not result.get("success"):
            return f"Search failed: {result.get('error')}"
        data = result.get("result") or {}
        rows = [f"Search results for: {data.get('query', '')}"]
        for index, item in enumerate(data.get("results", []), 1):
            rows.append(f"{index}. {item.get('title', '')}\nURL: {item.get('link', '')}\nSnippet: {item.get('snippet', '')}")
        if data.get("fallback"):
            rows.append("Note: search API credentials are not configured, so fallback search URLs were returned.")
        return "\n\n".join(rows)
